# Workflow temporarily disabled due to ongoing OpenSSL (FFI?) issue:
#
#   SSL_get_peer_certificate: implementation not found
#
# ---
#
# on:
#   push:
#   pull_request:

jobs:
  test-bot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: [ '8.4' ]
    name: Run test.rkt with Racket ${{ matrix.racket-version }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: x64
          version: ${{ matrix.racket-version }}
      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y libssl-dev
      - run: raco pkg install --deps search-auto
      - run: raco setup cordian
      - run: raco test test.rkt
